name: 'Hello World Docker Action'
description: 'Say something brother'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'BigKeFF'
outputs:
  time:
    description: 'The time we said hello.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
